services:
  db:
    image: postgres:15.1
    container_name: codequiz_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: codequiz_production
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "14052:5432"
    networks:
      - proxy-network
      - codequiz-network
  
  redis:
    image: redis:7
    container_name: codequiz_redis
    restart: always
    ports:
      - "14050:6379"
    networks:
      - proxy-network
      - codequiz-network

  web:
    build: .
    container_name: codequiz_web
    command: bash -c "echo 'RAILS_ENV='$RAILS_ENV && sleep 10 && bundle exec rails db:migrate && bundle exec rails s -e production -b 0.0.0.0 -p 3000"
    volumes:
      - .:/app
      - ./config/master.key:/app/config/master.key:ro
    ports:
      - "14051:3000"
    depends_on:
      - db
      - redis
    environment:
      RAILS_ENV: production
      NODE_ENV: production
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      DATABASE_URL: postgres://postgres:postgres@db:5432/codequiz_production
      DATABASE_HOST: db
      NODE_OPTIONS: --openssl-legacy-provider
      RAILS_SERVE_STATIC_FILES: true
      RAILS_LOG_TO_STDOUT: true
      VIRTUAL_HOST: www.codequiz.dockergp.ip-ddns.com
      LETSENCRYPT_HOST: www.codequiz.dockergp.ip-ddns.com
    networks:
      - proxy-network
      - codequiz-network

volumes:
  postgres_data:

networks:
  proxy-network:
    external: true
  codequiz-network:
    name: codequiz-network
    driver: bridge
    internal: true
