services:
  db:
    image: postgres:15.1
    container_name: codequiz_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: CodeQuiz_development
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: .
    container_name: codequiz_web
    command: bash -c "bundle exec rails db:prepare && bundle exec rails s -b 0.0.0.0"
    volumes:
      - .:/app
      - ./config/master.key:/app/config/master.key:ro
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_HOST: db
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
      RAILS_ENV: development
      NODE_ENV: development
      NODE_OPTIONS: --openssl-legacy-provider

volumes:
  postgres_data:
